# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Presto Blog
email: ""
description: >-
  Presto is a high performance, distributed SQL query engine for big data.
baseurl: "/blog"
url: "https://prestosql.io"
twitter_username: prestosql
github_username:  prestosql
google_analytics: UA-133457846-1
show_excerpts: true

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
